font_family FantasqueSansM Nerd Font
font_size 11.5
background_opacity 0.97
background_blur 1
clipboard_control write-clipboard read-clipboard


# Keybindings: Ctrl+N sends Ctrl-F (tmux prefix) + N
# map ctrl+1 send_text all \x06\x31
# map ctrl+2 send_text all \x06\x32
# map ctrl+3 send_text all \x06\x33
# map ctrl+4 send_text all \x06\x34
# map ctrl+5 send_text all \x06\x35

# Font zoom
map ctrl+plus    change_font_size all +1.0
map ctrl+equal   change_font_size all +1.0
map ctrl+minus   change_font_size all -1.0
map ctrl+0       change_font_size all 0



include themes/dankcolors.conf
include themes/noctalia.conf
