gesture SWIPE left 3  hyprctl dispatch workspace +1
gesture SWIPE right 3  hyprctl dispatch workspace -1
gesture SWIPE UP 3  hyprctl dispatch focusmonitor DP-3
gesture SWIPE DOWN 3  hyprctl dispatch focusmonitor eDP-1

