$primary_paletteKeyColor = 7FBBB3
$secondary_paletteKeyColor = 83C092
$tertiary_paletteKeyColor = A7C080
$neutral_paletteKeyColor = 2E383C
$neutral_variant_paletteKeyColor = 374145
$background = 2D353B
$onBackground = D3C6AA
$surface = 343F44
$surfaceDim = 232A2E
$surfaceBright = 475258
$surfaceContainerLowest = 1E2326
$surfaceContainerLow = 3B474E
$surfaceContainer = 3D484D
$surfaceContainerHigh = 475258
$surfaceContainerHighest = 4C5258
$onSurface = D3C6AA
$surfaceVariant = 3D484D
$onSurfaceVariant = 9DA9A0
$inverseSurface = D3C6AA
$inverseOnSurface = 2D353B
$outline = 859289
$outlineVariant = 475258
$shadow = 000000
$scrim = 000000
$surfaceTint = 7FBBB3
$primary = 7FBBB3
$onPrimary = 2D353B
$primaryContainer = 475258
$onPrimaryContainer = A7C080
$inversePrimary = 5A9A8F
$secondary = 83C092
$onSecondary = 2D353B
$secondaryContainer = 475258
$onSecondaryContainer = A7C080
$tertiary = A7C080
$onTertiary = 2D353B
$tertiaryContainer = 475258
$onTertiaryContainer = D3C6AA
$error = E67E80
$onError = 2D353B
$errorContainer = 4C3743
$onErrorContainer = E67E80
$primaryFixed = 7FBBB3
$primaryFixedDim = 5A9A8F
$onPrimaryFixed = 2D353B
$onPrimaryFixedVariant = 374145
$secondaryFixed = 83C092
$secondaryFixedDim = 5F8C6F
$onSecondaryFixed = 2D353B
$onSecondaryFixedVariant = 374145
$tertiaryFixed = A7C080
$tertiaryFixedDim = 7F9D5F
$onTertiaryFixed = 2D353B
$onTertiaryFixedVariant = 374145
$term0 = 2D353B
$term1 = E67E80
$term2 = A7C080
$term3 = DBBC7F
$term4 = 7FBBB3
$term5 = D699B6
$term6 = 83C092
$term7 = D3C6AA
$term8 = 859289
$term9 = E67E80
$term10 = A7C080
$term11 = DBBC7F
$term12 = 7FBBB3
$term13 = D699B6
$term14 = 83C092
$term15 = D3C6AA
$rosewater = D3C6AA
$flamingo = D699B6
$pink = D699B6
$mauve = D699B6
$red = E67E80
$maroon = E67E80
$peach = E69875
$yellow = DBBC7F
$green = A7C080
$teal = 83C092
$sky = 7FBBB3
$sapphire = 7FBBB3
$blue = 7FBBB3
$lavender = 7FBBB3
$klink = 7FBBB3
$klinkSelection = 7FBBB3
$kvisited = 83C092
$kvisitedSelection = 83C092
$knegative = E67E80
$knegativeSelection = E67E80
$kneutral = DBBC7F
$kneutralSelection = DBBC7F
$kpositive = A7C080
$kpositiveSelection = A7C080
$text = D3C6AA
$subtext1 = 9DA9A0
$subtext0 = 859289
$overlay2 = 7A8478
$overlay1 = 6F7A6F
$overlay0 = 5F6A5F
$surface2 = 3D484D
$surface1 = 343F44
$surface0 = 2D353B
$base = 2D353B
$mantle = 232A2E
$crust = 1E2326
$success = A7C080
$onSuccess = 2D353B
$successContainer = 475258
$onSuccessContainer = D3C6AA
