#!/usr/bin/env bash

export PATH="${PATH}:$HOME/.config/bspwm/bin"

pgrep -x sxhkd > /dev/null || sxhkd &

# bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor HDMI-0 -d '1' '2' '3'
bspc monitor DP-0 -d '4'
bspc config border_width 2
bspc config window_gap 10
bspc config window_gap_top 30
bspc config split_ratio 0.50

# bspc config focused_border_color "$BLUE" 
# bspc config normal_border_color "$BACKGROUND"
# bspc config active_border_color "$MAGENTA"
# bspc config presel_feedback_color "$GREEN"

bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config paddingless_monocle true
bspc config single_monocle false
bspc config focus_follows_pointer true


bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a firefox desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# Border
bspc config focused_border_color        "#7fbbb3"
bspc config normal_border_color         "#4b565c"
bspc config active_border_color         "#4b565c"


# App rules
bspc rule -a dota2 desktop='^2' follow=on focus=on state=floating

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &
# Bar
~/.config/polybar/launch.sh &
# Notifications
/usr/bin/dunst &
# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
# Wallpaper
nitrogen --restore &
# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  &
# Picom
picom --experimental-backends --config /home/kevin/.config/picom/picom.conf -b  &
# Network Applet
nm-applet --indicator &
# Cursor
xsetroot -cursor_name left_ptr &
# ~/.config/eww/arin/launch_bar &
# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh
