#!/usr/bin/env sh

# Unload the macOS WindowManager process
launchctl unload -F /System/Library/LaunchAgents/com.apple.WindowManager.plist >/dev/null 2>&1 &

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5

yabai -m config window_border_radius 0
yabai -m config layout bsp
yabai -m config window_gap 8
yabai -m config top_padding 40
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config active_window_border_topmost off
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow float
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config split_ratio 0.50
yabai -m config window_placement second_child
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 0.9
yabai -m config normal_window_opacity 0.9
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFFA7C080
yabai -m config insert_feedback_color 0xFFA3BE8C

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(LuLu|Calculator|Software Update|Dictionary|VLC|System Preferences|System Settings|zoom.us|Photo Booth|Archive Utility|Python|LibreOffice|App Store|Steam|Alfred|Activity Monitor)$" manage=off
yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off
yabai -m rule --add label="Select file to save to" app="^Inkscape$" title="Select file to save to" manage=off

yabai -m config layout bsp

echo "yabai configuration loaded.."
