#!/usr/bin/env sh
sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
#YABAI STUFF

# My custom space names for my 3 monitor setup. These names are used in some of my scripts.
yabai -m space 1 --label 1
yabai -m space 2 --label 2
yabai -m space 3 --label 3
yabai -m space 4 --label 4
yabai -m space 5 --label 5

# bsp or float (default: bsp)
yabai -m config window_border_radius 0
yabai -m config layout bsp
yabai -m config window_gap 8
yabai -m config top_padding 40
yabai -m config bottom_padding 8
yabai -m config left_padding 8
yabai -m config right_padding 8
yabai -m config active_window_border_topmost off
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_shadow float
yabai -m config focus_follows_mouse off
yabai -m config mouse_follows_focus off
yabai -m config split_ratio 0.50
yabai -m config window_placement second_child
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 0.9
yabai -m config normal_window_opacity 0.9
yabai -m config window_border on
yabai -m config window_border_width 2
yabai -m config active_window_border_color 0xFFA7C080
yabai -m config insert_feedback_color 0xFFA3BE8C
yabai -m config --space 4 layout float
yabai -m config --space 5 layout float

# float system preferences. Most of these just diable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Telegram$" space=^Float
yabai -m rule --add app="^Slack$" space=^Float
yabai -m rule --add app="^Finder$" space=^Float
yabai -m rule --add app="^brave$" space=^Float
yabai -m rule --add app="^1Password$" space=^Float
yabai -m rule --add app="^Calendar" space=^Float
yabai -m rule --add app="^Spotify$" space=^Float
yabai -m rule --add app="^NextEditor$" space=^Browser
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^Dota2$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on manage=off
yabai -m rule --add app="^Skype" manage=off
yabai -m rule --add app="^CleanMyMac X$" manage=off
yabai -m rule --add app="^Private Internet Access$" manage=off

#find ~/Library/Parallels/Applications\ Menus/ -maxdepth 3 -type f | awk -F'/' '{ print $NF; }' | awk '{$1=$1};1' | sort | uniq | tr "\n" "\0" | xargs -0 -I{} yabai -m rule --add app="^{}\$" title=".*" manage=on

## some other settings
yabai -m config auto_balance off
# # set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier ctrl
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# set modifier + left-click drag to resize window (default: move)
yabai -m config mouse_action1 move

# general space settings
#yabai -m config focused_border_skip_floating  1
#yabai -m config --space 3 layout             float

## Change how yabai looks

echo "yabai configuration loaded.."

#END
