-- require("items.widgets.brew")
require("items.widgets.battery")
require("items.widgets.volume")
-- require("items.widgets.mic")
require("items.widgets.wifi")
require("items.widgets.cpu")
-- require("items.widgets.ram")
-- require("items.widgets.ssd")
-- require("items.widgets.weather")
