monitor=HDMI-A-1,2560x1440,0x0,1
monitor=eDP-1,2240x1400,2560x0,auto

# MONITOR
workspace = 1, monitor:HDMI-A-1
workspace = 2, monitor:HDMI-A-1
workspace = 3, monitor:HDMI-A-1
workspace = 4, monitor:eDP-1
