$SCRIPT = ~/.config/HyprV/waybar/scripts

binde=,XF86AudioRaiseVolume, exec, swayosd-client --output-volume raise
binde=,XF86AudioLowerVolume, exec, swayosd-client --output-volume lower

bind = , xf86AudioMicMute, exec, swayosd-client --input-volume mute-toggle
bind = , xf86audioMute, exec, swayosd-client --output-volume mute-toggle 
bind = , Caps_Lock, exec, swayosd-client --caps-lock
bind = , Caps_Lock, exec, swayosd-client --caps-lock-led input19::capslock

bind = , xf86KbdBrightnessDown, exec, swayosd-client --brightness lower 
bind = , xf86KbdBrightnessUp, exec, swayosd-client --brightness raise 

bind = , xf86MonBrightnessDown, exec, swayosd-client --brightness lower 
bind = , xf86MonBrightnessUp, exec, swayosd-client --brightness raise 
