background #2d353b
foreground #d3c6aa
cursor #a7c080
selection_background #a7c080
selection_foreground #d3c6aa

color0 #232a2e
color1 #dc7763
color2 #67c060
color3 #f0dd6b
color4 #99b66d
color5 #435822
color6 #a7c080
color7 #c4c9bd
color8 #81847b
color9 #ffaf9f
color10 #9ce695
color11 #fff2a5
color12 #bbd397
color13 #e2f9bf
color14 #f0ffd8
color15 #fcfff8
