color0 #4f585e
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #d3c6aa
color8 #7a8478
color9 #e67e80
color10 #a7c080
color11 #dbbc7f
color12 #7fbbb3
color13 #d699b6
color14 #83c092
color15 #e4dcc5

cursor                #d3c6aa
cursor_text_color     #2d353b
background            #2d353b
foreground            #d3c6aa
selection_foreground  #d3c6aa
selection_background  #475258
active_border_color   #a7c080
inactive_border_color #3d484d
url_color             #a7c080

active_tab_foreground   #2d353b
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #3d484d
cursor_trail_color      #d3c6aa
