color0 #7a8478
color1 #e67e80
color2 #a7c080
color3 #dbbc7f
color4 #7fbbb3
color5 #d699b6
color6 #83c092
color7 #f2efdf
color8 #a6b0a0
color9 #f85552
color10 #8da101
color11 #dfa000
color12 #3a94c5
color13 #df69ba
color14 #35a77c
color15 #fffbef

cursor                #e69875
cursor_text_color     #4c3743
background            #1e2326
foreground            #d3c6aa
selection_foreground  #d3c6aa
selection_background  #4c3743
active_border_color   #a7c080
inactive_border_color #2d353b
url_color             #a7c080

active_tab_foreground   #232a2e
active_tab_background   #a7c080
inactive_tab_foreground #d3c6aa
inactive_tab_background #2d353b
cursor_trail_color      #d3c6aa
